config/routes.rb
Rails.application.routes.draw do
  get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'top/login'
  get 'users/index'
  get 'users/me'
  get 'sessions/create'
  get 'sessions/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :users
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/good_lang_relation.rb
class GoodLangRelation < ApplicationRecord
  belongs_to :user
  belongs_to :program_lang
end

app/models/learn_lang_relation.rb
class LearnLangRelation < ApplicationRecord
  belongs_to :user
  belongs_to :program_lang
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :users
end

app/models/program_lang.rb
class ProgramLang < ApplicationRecord
  has_many :good_lang_relations
  has_many :good_langs, through: :good_lang_relations, source: :users
  has_many :learn_lang_relations
  has_many :learn_langs, through: :learn_lang_relations, source: :users
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :prefecture, optional: true
  has_many :good_lang_relations, dependent: :destroy
  has_many :good_langs, through: :good_lang_relations, source: :program_lang, dependent: :destroy
  has_many :learn_lang_relations, dependent: :destroy
  has_many :learn_langs, through: :learn_lang_relations, source: :program_lang, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  #has_many :program_langs, through: :good_lang_relations
  #has_many(:good_langs, {:through => :good_lang_relations, :source => :program_lang})

  enum gender: { male: 1, female: 2 }
  mount_uploader :image, ImageUploader

  validates :email,
    { :presence => true,
      :uniqueness => true,
        :length => { :maximum => 32 },
        format: {
        with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
        message: 'が不正な形式です'
        }
    }
  validates :password,
    length: { minimum: 8}

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  private

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  #before_action :authenticate_user!, :only => [:create]

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  #before_action :@current_user.authenticate
  def index
    @currentEntries = @current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end

    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?', @current_user.id)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      flash[:danger] = 'Invalid email/password combination' 
      redirect_to top_login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def login
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @search = User.ransack(params[:q])
    @good_langs = GoodLangRelation.all
    @users = @search.result(distinct: true).includes(:good_langs) #この行を修正

    #respond_to do |format|
     # format.html # index.html.erb
      #format.json { render json: @users }
    #end
  end

  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    
    #good_lang = GoodLangRelation.new()
    if user.save
      session[:user_id] = user.id
      redirect_to mypage_path
    else
      redirect_back fallback_location: root_path, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: @current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == @current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def me
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      redirect_to  users_me_path
    else
      redirect_back fallback_location: root_path, flash: {
        user: @user,
        error_messages: @user.errors.full_messages
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :prefecture_id, :user_name, :age,
                                 :gender, :image, :introduction, good_lang_ids: [], learn_lang_ids: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/_header.html.erb
<%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Montserrat:400,400i,500,500i,600,600i,700,700i", :media => "all" %>
<%= stylesheet_link_tag "me/header/font-awesome.min.css", :media => "all" %>
<%= stylesheet_link_tag "me/header/flaticon.css", :media => "all" %>
<%= stylesheet_link_tag "me/header/style.css", :media => "all" %>

<header class="header-section">
  <div class="container">
    <!-- Site Logo -->
    <div class="site-logo">
      <%= image_tag("/images/logo.PNG", :size => "115x55") %>
    </div>

    <!-- Main Menu -->
    <ul class="main-menu">    
			<li><%= link_to "言語友達検索", users_index_path %></li>

			<li><%= link_to "メッセージ", rooms_path %></li>

			<li><%= link_to "マイページ", users_me_path %></li>  
      
      <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
    </ul>

  </div>
	<hr style="margin:-20px"><br>
</header>

app/views/rooms/index.html.erb
<%= render 'header' %>
<%= stylesheet_link_tag "dm/dmList.css", :media => "all" %>

<div class="body">
<div text-align: center;><h2>メッセージ一覧 </h2> </div>
<div class="container page-container">
<div class="row gutters">
<% @anotherEntries.each do |e| %>
  <% user = "user-card green" %>
  <% colors = ["user-card green", "user-card blue", "user-card red", "user-card yellow", "user-card orange", "user-card teal", "user-card pink", "user-card yellow", "user-card brown", "user-card purple"] %>
  <% colors.shuffle! %>
    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4 col-12">
      <figure class='<%= colors[0] %>'>
	  		<figcaption>
      		<%= image_tag(e.user.image.to_s, :class => "profile") %>
	  				<h5><%= e.user.user_name %></h5>
	  				<h6><% if e.user.gender == 'male' %>男 <% else %>女 <% end %><%= e.user.age %>歳</h6>

	  				<ul class="contacts">
	  					<li>
        	  	<%= link_to room_path(e.room.id) do %>
        	    	チャットへ
        	  	<% end %>
	  					</li>
	  				</ul>
	  		</figcaption>
	  	</figure>
  	</div>
<% end %>

</div>
</div>
</div>

app/views/rooms/show.html.erb
<%= render 'shared/error_messages' %>
<%= render 'header' %>
<%= stylesheet_link_tag "dm/dm.css", :media => "all" %>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<hr class="">
<div class="container">
<h3 class=" text-center">Messaging</h3>
<div class="messaging">
      <div class="inbox_msg">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading">
              <h4>Recent</h4>
            </div>
            
          </div>
					<div class="inbox_chat">
					<% if @messages.present? %>
            <% @messages.each do |m| %>
              <% if m.user_id != @current_user.id %>
            		<div class="chat_list">
            		  <div class="chat_people">
            		    <div class="chat_img"> <%= image_tag(m.user.image.to_s, :class => "img-circle img-sm") %> </div>
            		    <div class="chat_ib">
            		      <h5><%= m.user.user_name %><span class="chat_date"><%= m.created_at %></span></h5>
            		      <p><%= m.content %></p>
            		    </div>
            		  </div>
								</div>
							<% end %>
						<% end %>
					<% end %>
          </div>
        </div>
        <div class="mesgs">
					<div class="msg_history">
					<% if @messages.present? %>
            <% @messages.each do |m| %>
              <% if m.user_id != @current_user.id %>
            		<div class="incoming_msg">
            		  <div class="incoming_msg_img"> <%= image_tag(m.user.image.to_s, :class => "img-circle img-sm") %> </div>
            		  <div class="received_msg">
            		    <div class="received_withd_msg">
            		      <p><%= m.content %></p>
            		      <span class="time_date"><%= m.created_at %></span></div>
            		  </div>
								</div>
							<% else %>
								<div class="outgoing_msg">
              		<div class="sent_msg">
              	  	<p><%= m.content %></p>
              	  	<span class="time_date"><%= m.created_at %></span> </div>
            		</div>
							<% end %>
						<% end %>
					<% end %>
        	</div>
          <div class="type_msg">
						<div class="input_msg_write">
							<%= form_for @message do |f| %>								
								<%= f.text_field :content, :class => "write_msg", :placeholder => "Type a message"%>
								<%= f.hidden_field :room_id, :value => @room.id %>
								<%= button_tag :type => "submit", :class => "msg_send_btn" do %>
									<i class="fa fa-paper-plane-o"></i>
								<% end %>
							<% end %>
            </div>
          </div>
        </div>
			</div>
			
    </div></div>

app/views/top/index.html.erb
<nav class="navbar navbar-default navbar-transparent navbar-fixed-top" color-on-scroll="200">
  <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"-->
  <div class="container">
    <div class="navbar-header">
      <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar bar1"></span>
        <span class="icon-bar bar2"></span>
        <span class="icon-bar bar3"></span>
      </button>
      <a href="#" class="navbar-brand">
        PuPuMu
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right navbar-uppercase">
        <% if @current_user %>
          <li>
            <a href="rooms#index">メッセージ</a>
          </li>
          <li class="dropdown">
            <a href="/users/me" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-share-alt"></i> マイページ
            </a>
            <ul class="dropdown-menu dropdown-danger">
              <li>
                <a href="#"><i class="fa fa-facebook-square"></i> Facebook</a>
              </li>
              <li>
                <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
              </li>
              <li>
                <a href="#"><i class="fa fa-instagram"></i> Instagram</a>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-danger btn-fill' %>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="/top/login">ログイン</a>
          </li>
          <li>
            <a href="/users/new" class="btn btn-danger btn-fill">会員登録</a>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
</nav>


<div class="section section-header">
  <div class="parallax filter filter-color-black">
    <div class="image"
      style="background-image: url(/images/office-1.jpeg)">
    </div>
    <div class="container">
      <div class="content">
        <div class="title-area">
          <p></p>
          <h1 class="title-modern">PuPuMu</h1>
          <h3 class="about1">
          PuPuMuはペアプログラミングマッチングサービスです。
          <br>お互いの得意なプログラム言語を教え合おう！
          </h3>
          <div class="separator line-separator">♦</div>
        </div
        <div class="button-get-started">
          <a href="/users/new" class="btn btn-white btn-fill btn-lg ">
            <i>PuPuMuをはじめる<i>
          </a>
        </div>
      </div
    </div>
  </div>
</div>

app/views/top/login.html.erb
<%= render 'shared/error_messages' %>
<%= stylesheet_link_tag "login/login.css", :media => "all" %>

<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<body id="LoginForm">
<div class="container">
  <div class="login-form">
    <div class="main-div">
      <div class="panel">
        <h2>Admin Login</h2>
        <p>Please enter your email and password</p>
      </div>

      
      <%= form_for(:session, method: :post, url: login_path) do |f| %>
        <div class="form-group">   
          <%= f.text_field :email, class:'form-control', placeholder: "Email Address" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password , class:'form-control', placeholder: "Password" %>          
        </div>
        <br>
        <%= f.submit 'Login', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>
</body>

app/views/users/_header.html.erb
<%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Montserrat:400,400i,500,500i,600,600i,700,700i", :media => "all" %>
<%= stylesheet_link_tag "me/header/font-awesome.min.css", :media => "all" %>
<%= stylesheet_link_tag "me/header/flaticon.css", :media => "all" %>
<%= stylesheet_link_tag "me/header/style.css", :media => "all" %>


<header class="header-section">
  <div class="container">
    <!-- Site Logo -->
    <div class="site-logo">
      <%= image_tag("/images/logo.PNG", :size => "115x55") %>
    </div>

    <!-- Main Menu -->
    <ul class="main-menu">
			<li><%= link_to "言語友達検索", users_index_path %></li>

      <li><%= link_to "メッセージ", rooms_path %></li>
      
			<li><%= link_to "マイページ", users_me_path %></li>  
      
      <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
    </ul>

  </div>
	<hr style="margin:-20px"><br>
</header>

app/views/users/index.html.erb
<%= render 'shared/error_messages' %>
<%= render 'header' %>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<!------ Include the above in your HEAD tag ---------->

<div class="container">
	<div class="row">
		<h1 align="center">言語友達検索</h1> <br/>

    <div class="container">
    <%= search_form_for @search, url: users_index_path do |f| %>    
      <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-3"></div>
        <div class="col-md-3 col-sm-3 col-xs-3 sec">
          <%= f.label :user_name_cont, 'ユーザー名(表示名)' %>
          <%= f.text_field :user_name_cont, class: 'form-control' %>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-3 sec">
          <%= f.label :gender_eq, '性別' %><br>
          <div class="radio-inline">
            <%= f.radio_button :gender_eq, '' %>
            <%= f.label :gender_eq, '指定なし' %>
          </div>
          <div class="radio-inline">
            <%= f.radio_button :gender_eq, '1' %>
            <%= f.label :male, '男性' %>
          </div>      
          <div class="radio-inline">
            <%= f.radio_button :gender_eq, '2' %>
            <%= f.label :female, '女性' %>
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-3"></div>
      </div>
    
      <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-3"></div>
        <div class="col-xs-1">
          <%= f.label :age_gteq, '年齡 from' %>
          <%= f.select(:age_gteq, options_for_select((18..85).to_a), {prompt: ""}, {class: 'form-control'}) %>
        </div>
        <div class="col-xs-1">
          <%= f.label :age_lteq, 'to' %>
          <%= f.select(:age_lteq, options_for_select((18..85).to_a), {prompt: ""}, {class: 'form-control'}) %>
        </div>
        <div class="col-md-1 col-sm-3 col-xs-3"></div>
        <div class="col-md-1 col-sm-1 col-xs-6">
          <%= f.label :prefecture_id_eq, '地域' %><br>
          <%= f.collection_select(:prefecture_id_eq, Prefecture.all, :id, :name, {prompt: "未選択"}, {class: 'form-control'}) %>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-3"></div>
      </div>

      <div class="row">
      <div class="col-md-3 col-sm-3 col-xs-3"></div>
        <div class="col-md-8 col-sm-6 col-xs-6">
          <%= f.label :good_lang, "得意言語" %><br>
          <%= f.collection_check_boxes :good_langs_id_in, ProgramLang.all, :id, :name %>  
        </div>
        <div class="col-md-3 col-sm-3 col-xs-3"></div>
      </div>
      
      <div class="row">
      <div class="col-md-3 col-sm-3 col-xs-3"></div>
        <div class="col-md-8 col-sm-6 col-xs-6">
          <%= f.label :good_lang, "学びたい言語" %><br>
          <%= f.collection_check_boxes :learn_langs_id_in, ProgramLang.all, :id, :name %>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-3"></div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-5"></div>
        <div class="col-md-2 col-sm-2 col-xs-3"><button type="submit" class="btn btn-primary">検索する</button></div>
        <div class="col-md-5 col-sm-5 col-xs-35"></div>
      </div>
        
    </div>
  <% end %>
	</div>
</div>

<br><br>
<% @users.each do |u| %> 
  <table class="table">
    <tbody> 
    <tr>
      <td>
      <% if u.image? %>
        <div class="media">
          <a class="pull-left" href="/users/<%= u.id %>">
            <%= image_tag(u.image.to_s, :size => "100x100", :class => "media-object dp img-circle") %>
          </a>
      <% else %>
        <div class="media">
          <a class="pull-left" href="/users/<%= u.id %>">
            <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="media-object dp img-circle" width="100" hegith="100">
          </a>
      <% end %>
          <div class="media-body">
            <h4 class="media-heading"><%= u.user_name %> <small> <%= u.age %>歳 </small></h4>
            <h5>
              【地域】<%= u.prefecture.name %>
              【性別】<% if u.gender == 'male' %>男性<% else %>女性<% end %>
            </h5>
            <hr style="margin:8px auto">
            <strong>得意　　</strong>
            <% u.good_langs.each do |pg| %>
              <h6 id="badge"><span class="label label-primary"><%= pg.name %></span></h6>
            <% end %><br>
            <strong>学びたい</strong>
            <% u.learn_langs.each do |pg| %>
              <h6 id="badge"><span class="label label-warning"><%= pg.name %></span></h6>
            <% end %>
          </div>
        </div>
      </td>
    </tr>
  </table> 
<% end %>

app/views/users/me.html.erb
<%= render 'shared/error_messages' %>
<%= render 'header' %>
<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :media => "all" %>
<script type="text/javascript">
  $(document).on('change', ':file', function() {
      var input = $(this),
      numFiles = input.get(0).files ? input.get(0).files.length : 1,
      label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
      input.parent().parent().next(':text').val(label);
  });
</script>

<div class="container bootstrap snippet">
  <div class="row">
  	<div class="col-sm-10"><h1><%= @current_user.user_name %></h1></div>
  </div>
  <div class="row">
  	<div class="col-sm-3"><!--left col-->

      <div class="text-center">
      <%= form_for @current_user do |f| %>
        <% if @current_user.image? %>
          <%= image_tag(@current_user.image.to_s, :size => "200x100", :class => "avatar img-circle img-thumbnail") %>
          <h6></h6>
          <div class="input-group">
            <label class="input-group-btn">
              <span class="btn btn-primary">
                画像変更<%= f.file_field :image, :style => "display:none" %>
              </span>
            </label>
            <input type="text" class="form-control" readonly="">
          </div>
        <% else %>
          <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
          <div class="input-group">
            <label class="input-group-btn">
              <span class="btn btn-primary">
                画像登録<%= f.file_field :image, :style => "display:none" %>
              </span>
            </label>
            <input type="text" class="form-control" readonly="">
          </div>
        <% end %>
      
      </div></hr><br>  

      <div class="panel panel-default">
        <div class="panel-heading">Social Media</div>
        <div class="panel-body">
        	<i class="fa fa-facebook fa-2x"></i> <i class="fa fa-github fa-2x"></i> <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i> <i class="fa fa-google-plus fa-2x"></i>
        </div>
      </div>
    </div><!--/col-3-->

  	<div class="col-sm-9">

      <div class="tab-content">
        <div class="tab-pane active" id="home">
          <hr>
            <div class="form-group">
              <div class="col-xs-6">
                <label for="nickname"><h4>ユーザー名 (表示名)</h4></label>
                <%= f.text_field :user_name, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-6">
                <label for="last_name"><h4>地域</h4></label>
                <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {prompt: ""}, {class: 'form-control'}) %> 
              </div>
            </div>
        
            <div class="form-group">
              <div class="col-xs-12">
                <label for="good_lang"><h4>得意言語</h4></label><br>
                <%= f.collection_check_boxes(:good_lang_ids, ProgramLang.all, :id, :name) do |n| %>
                  <div class="checkbox-inline">
                    <%= n.label do %>
                      <%= n.check_box %>
                      <%= n.text %>
                    <% end %>          
                  </div>
                <% end %>
              </div>
            </div>
                        
            <div class="form-group">        
              <div class="col-xs-12">
                <label for="learn_lang"><h4>学びたい言語</h4></label><br>
                <%= f.collection_check_boxes(:learn_lang_ids, ProgramLang.all, :id, :name) do |n| %>
                  <div class="checkbox-inline">
                    <%= n.label do %>
                      <%= n.check_box %>
                      <%= n.text %>
                    <% end %>          
                  </div>
                <% end %>
              </div>
            </div>
            <div class="form-group">        
              <div class="col-xs-12">
                <label for="learn_lang"><h4>自己紹介</h4></label><br>
                <%= f.text_area :introduction, :size => "75x5" %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-6">
              <%= f.label :password, 'パスワード' %>
              <%= f.password_field :password, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-6">
              <%= f.label :password_confirmation, '確認用パスワード' %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
              </div>
            </div>
                        
            <div class="form-group">
              <div class="col-xs-12">
                <br>
                <%= f.submit 'SAVE', class: 'btn btn-lg btn-success' %>
              </div>
            </div>
          <% end %>
                              
          <hr>
                              
         </div><!--/tab-pane-->
      </div><!--/tab-content--  
    </div><!--/col-9-->
  </div><!--/row-->
</div>